### PR TITLE
Fix #418 One gradle task

### LINKED ISSUE #418: One gradle task

### PR DESCRIPTION
**Pull request by ComLock**

### CODE REVIEW

**Review by alansemenov — CHANGES_REQUESTED** [review]
The build is failing. Does it need a new version of the lib?

```
npm ERR! Missing script: "build:react4xp"
```

**Comment by ComLock** [comment]
Nope, we need a new version of the build system :)

**Comment by rymsha** [comment]
> The build is failing. Does it need a new version of the lib?
> 
> ```
> npm ERR! Missing script: "build:react4xp"
> ```

it requires https://github.com/enonic/enonic-react4xp/pull/205

**Review by rymsha — CHANGES_REQUESTED** [review]
I couldn't build until I added  `"swc-loader": "^0.2.3",` into package.json

**Comment by ComLock** [comment]
This needs a new release of @enonic/react4xp to build

The only reason it complains about swc-loader is because you used npm link, or an old version of the build system.

**Review by rymsha — APPROVED** [review]

**Review by rymsha — APPROVED** [review]

**Review by rymsha — APPROVED** [review]

**Pull request merged**
